// <auto-generated />
using System;
using Antifraude.Infra.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Antifraude.Infra.Persistencia.Migrations
{
    [DbContext(typeof(AntifraudeDbContext))]
    [Migration("20260709181326_ClassificacaoRisco")]
    partial class ClassificacaoRisco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Antifraude.Core.Dominio.Caso", b =>
                {
                    b.Property<Guid>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("case_id");

                    b.Property<bool>("CoberturaParcial")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("cobertura_parcial");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em");

                    b.Property<bool>("DadosIncompletos")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("dados_incompletos");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("estado");

                    b.Property<string>("Explicacao")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("explicacao");

                    b.Property<string>("Faixa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("faixa");

                    b.Property<string>("Motivo")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("motivo");

                    b.Property<bool>("PayloadParcial")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("payload_parcial");

                    b.Property<string>("Rota")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("rota");

                    b.Property<int?>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.Property<int>("VersaoConfig")
                        .HasColumnType("int")
                        .HasColumnName("versao_config");

                    b.Property<string>("VersaoProvider")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("versao_provider");

                    b.Property<string>("VersaoTemplate")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("versao_template");

                    b.HasKey("CaseId");

                    b.ToTable("casos", (string)null);
                });

            modelBuilder.Entity("Antifraude.Core.Dominio.RegistroAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Ator")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("ator");

                    b.Property<DateTimeOffset>("CarimbadoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("carimbado_em");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("char(36)")
                        .HasColumnName("case_id");

                    b.Property<string>("Causa")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("causa");

                    b.Property<bool>("CoberturaParcial")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("cobertura_parcial");

                    b.Property<string>("Explicacao")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("explicacao");

                    b.Property<string>("Faixa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("faixa");

                    b.Property<string>("Motivo")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("motivo");

                    b.Property<bool>("PayloadParcial")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("payload_parcial");

                    b.Property<string>("Rota")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("rota");

                    b.Property<int?>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.Property<string>("Sinais")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("sinais_json");

                    b.Property<int>("VersaoConfig")
                        .HasColumnType("int")
                        .HasColumnName("versao_config");

                    b.Property<string>("VersaoProvider")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("versao_provider");

                    b.Property<string>("VersaoTemplate")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("versao_template");

                    b.HasKey("Id");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_auditoria_case_id");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("Antifraude.Core.Dominio.RegistroIngestao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("char(36)")
                        .HasColumnName("case_id");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("destino");

                    b.Property<string>("IdSinistro")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("id_sinistro");

                    b.Property<string>("Idempotencia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idempotencia");

                    b.Property<bool>("PayloadParcial")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("payload_parcial");

                    b.Property<DateTimeOffset>("RecebidoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("recebido_em");

                    b.Property<bool>("TemAparelho")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("tem_aparelho");

                    b.Property<bool>("TemApolice")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("tem_apolice");

                    b.Property<bool>("TemFotos")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("tem_fotos");

                    b.Property<bool>("TemMetadados")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("tem_metadados");

                    b.HasKey("Id");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_auditoria_ingestao_case_id");

                    b.HasIndex("IdSinistro")
                        .HasDatabaseName("ix_auditoria_ingestao_id_sinistro");

                    b.ToTable("auditoria_ingestao", (string)null);
                });

            modelBuilder.Entity("Antifraude.Core.Dominio.ScoringConfig", b =>
                {
                    b.Property<int>("Versao")
                        .HasColumnType("int")
                        .HasColumnName("versao");

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativa");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criada_em");

                    b.Property<int>("LimiarAlto")
                        .HasColumnType("int")
                        .HasColumnName("limiar_alto");

                    b.Property<int>("LimiarMedio")
                        .HasColumnType("int")
                        .HasColumnName("limiar_medio");

                    b.Property<string>("Pesos")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("pesos_json");

                    b.HasKey("Versao");

                    b.HasIndex("Ativa")
                        .HasDatabaseName("ix_scoring_config_ativa");

                    b.ToTable("scoring_config", (string)null);
                });

            modelBuilder.Entity("Antifraude.Infra.Persistencia.ApoliceRegistro", b =>
                {
                    b.Property<string>("Apolice")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apolice");

                    b.Property<string>("Imei")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("imei");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("numero_serie");

                    b.HasKey("Apolice");

                    b.ToTable("apolices", (string)null);
                });

            modelBuilder.Entity("Antifraude.Infra.Persistencia.HistoricoSinistroRegistro", b =>
                {
                    b.Property<string>("IdSinistro")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("id_sinistro");

                    b.Property<DateTimeOffset>("AbertoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("aberto_em");

                    b.Property<string>("IdCliente")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Imei")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("imei");

                    b.HasKey("IdSinistro");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("ix_historico_sinistros_id_cliente");

                    b.HasIndex("Imei")
                        .HasDatabaseName("ix_historico_sinistros_imei");

                    b.ToTable("historico_sinistros", (string)null);
                });

            modelBuilder.Entity("Antifraude.Infra.Persistencia.ImagemHashRegistro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em");

                    b.Property<string>("FotoRef")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("foto_ref");

                    b.Property<string>("IdSinistro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("id_sinistro");

                    b.Property<long>("Phash")
                        .HasColumnType("bigint")
                        .HasColumnName("phash");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm")
                        .HasDatabaseName("ix_imagem_hashes_criado_em");

                    b.HasIndex("IdSinistro", "FotoRef")
                        .IsUnique()
                        .HasDatabaseName("ux_imagem_hashes_sinistro_foto");

                    b.ToTable("imagem_hashes", (string)null);
                });

            modelBuilder.Entity("Antifraude.Infra.Persistencia.SinistroProcessado", b =>
                {
                    b.Property<string>("IdSinistro")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("id_sinistro");

                    b.Property<DateTimeOffset>("PrimeiraVezEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("primeira_vez_em");

                    b.HasKey("IdSinistro");

                    b.HasIndex("PrimeiraVezEm")
                        .HasDatabaseName("ix_sinistros_processados_primeira_vez_em");

                    b.ToTable("sinistros_processados", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
